name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile CV
        uses: xu-cheng/latex-action@v4
        with:
          root_file: CV_Julien.tex
      - name: Upload Pdf
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv.pdf
